1. The probability that it is Friday and that a student is absent is 3 %. Since there are 5
school days in a week, the probability that it is Friday is 20 %. What is the probability that a
student is absent given that today is Friday? Apply Bayes rule in python to get the result.


In [7]:
probAbsentFriday = 0.03
probFriday = 0.2

bayesResult = probAbsentFriday / probFriday

print(bayesResult * 100)

15.0


2. Implement an algorithm to demonstrate the significance of SVM.

In [8]:
import numpy as np
import pandas as pd

Importing iris dataset

In [11]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target

Splitting into training and testing data

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

Standardizing the dataset

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

Fitting the data

In [14]:
from sklearn.svm import SVC
model = SVC()
model.fit(X_train, y_train)
result = model.predict(X_test)

Calculating Metrics

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
print('Confusion matrix = \n', confusion_matrix(result, y_test))
print('Accuracy = ', accuracy_score(result, y_test))

Confusion matrix = 
 [[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
Accuracy =  0.9666666666666667


plot_decision_boundary(svm_classifier, X_test, y_test, title='SVM Decision Boundary')