Creating a dataset

Features: (Using a Classification Problem)

1. Study Hours
2. Previous Test Score
3. Pass/Fail

In [1]:
import numpy as np

np.random.seed(42)
Study_Hours = np.random.randint(1,8,100)
Test_Score = np.random.randint(40,100,100)
Result = np.where(Study_Hours + Test_Score > 100, 1, 0)

Splitting data for training and testing

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(np.column_stack((Study_Hours, Test_Score)), Result, test_size = 0.2, random_state = 42)

Trying out different models:

1. Logistic Regression

In [3]:
from sklearn.linear_model import LogisticRegression

model1 = LogisticRegression()
model1.fit(X_train, y_train)
result1 = model1.predict(X_test)

In [4]:
result1

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

2. Decision Tree

In [5]:
from sklearn.tree import DecisionTreeClassifier

model2 = DecisionTreeClassifier()
model2.fit(X_train, y_train)
result2 = model2.predict(X_test)

In [6]:
result2

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

3. Random Forest

In [7]:
from sklearn.ensemble import RandomForestClassifier

model3 = RandomForestClassifier()
model3.fit(X_train, y_train)
result3 = model3.predict(X_test)

In [8]:
result3

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

METRICS CALCULATIONS:

In [9]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("Metrics Calculations")

Metrics Calculations


In [10]:
print("1. Logistic Regression")
print("Accuracy = ", accuracy_score(result1, y_test))
print("Precision = ", precision_score(result1, y_test))
print("Recall = ", recall_score(result1, y_test))
print("F1-Score = ", f1_score(result1, y_test))

1. Logistic Regression
Accuracy =  0.95
Precision =  1.0
Recall =  0.5
F1-Score =  0.6666666666666666


In [11]:
print("2. Decision Tree")
print("Accuracy = ", accuracy_score(result2, y_test))
print("Precision = ", precision_score(result2, y_test))
print("Recall = ", recall_score(result2, y_test))
print("F1-Score = ", f1_score(result2, y_test))

2. Decision Tree
Accuracy =  0.95
Precision =  1.0
Recall =  0.5
F1-Score =  0.6666666666666666


In [12]:
print("3. Random Forest")
print("Accuracy = ", accuracy_score(result3, y_test))
print("Precision = ", precision_score(result3, y_test))
print("Recall = ", recall_score(result3, y_test))
print("F1-Score = ", f1_score(result3, y_test))

3. Random Forest
Accuracy =  0.95
Precision =  1.0
Recall =  0.5
F1-Score =  0.6666666666666666
